DROP SEQUENCE QRTZ_JOB_HISTORY_SEQ;
CREATE SEQUENCE QRTZ_JOB_HISTORY_SEQ;

DROP TABLE QRTZ_JOB_HISTORY;
CREATE TABLE QRTZ_JOB_HISTORY (
  ENTRY_ID VARCHAR (95)  NOT NULL ,
  HOSTNAME VARCHAR (250),
  IP_ADDR VARCHAR (250),
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR (200)  NOT NULL ,
  JOB_NAME VARCHAR (200)  NULL ,
  JOB_GROUP VARCHAR (200)  NULL ,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  FIRED_TIME TIMESTAMP NOT NULL ,
  NEXT_FIRE_TIME TIMESTAMP,
  PRIORITY INTEGER NOT NULL ,
  IS_NONCONCURRENT BOOLEAN  NULL ,
  REQUESTS_RECOVERY BOOLEAN  NULL,
  RESULT VARCHAR (250) NOT NULL,
  EXCEPTIONS VARCHAR (2500)
);
